apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-app
  name: mysql-app
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: mysql-app
  type: NodePort
status:
  loadBalancer: {}
