# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   ports:
#     - port: 3306
#   selector:
#     app: mysql
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - image: mysql:latest
#           name: mysql
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               value: rishabh@123
#           ports:
#             - containerPort: 3306
#               name: mysql
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: grant-permissions
# spec:
#   template:
#     spec:
#       containers:
#       - name: grant-permissions
#         image: mysql:latest
#         command: ["sh", "-c", "mysql -u root -prishabh@123 -h mysql -e 'GRANT ALL PRIVILEGES ON *.* TO '*'@'%' WITH GRANT OPTION;'"]
#       restartPolicy: Never
