apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 48483/weatherwisebackend:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8082


---

apiVersion: v1 
kind: Service
metadata:
  name: backend-ssvc
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 8082 
      targetPort: 8082
  type: LoadBalancer 
