apiVersion: v1
kind: Service
metadata:
  name: backend-ssvc
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: 48483/weatherwisebackend:latest
          name: backend
          ports:
            - containerPort: 8082
