version: '3.8'

services:
  app:
    image: 48483/temp:latest
    ports:
      - 8082:8082
    environment:
      DB_URL: jdbc:mysql://db:3306/weatherwise?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      DB_USERNAME: root
      DB_PASSWORD: Rishabh@1234
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: Rishabh@1234
      MYSQL_DATABASE: weatherwise
      MYSQL_USER: admin
      MYSQL_PASSWORD: Rishabh@1234

