spring:
  application:
    name: WeatherWise

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weatherwise?useSSL=false
    username: root
    password: 1234
    hikari:
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
  port: 8082
