spring:
  config:
    import:
      configserver:
  application:
    name: WeatherWise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/weatherwise?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

## Server Configuration ##
server:
  servlet:
    context-path: /api
  port: 8082
